SELECT
 cq.CBS_MODULE, cq.SEVERITY, cq.PRIORITY, cq.ID, cq.TITLE, cq.SERVICE_NAME, s.NAME, cq.STATE, cq.SUBMIT_DATE,cq.CUSTOMER_NAME,cq.ASSIGN_TO_FULLNAME, cq.DBID
FROM CQ_RO.CBS_DEFECT cq, CQ_RO.STATEDEF s
WHERE
 (cq.PRODUCT_NAME='Comverse ONE CV-RT-FX') AND (s.ID=cq.state) AND (DEFECT_TYPE='PR') AND (s.NAME = 'Ready4Packaging' AND cq.SERVICE_NAME='Self Service' AND cq.CUSTOMER_NAME='GA'AND cq.CBS_MODULE='CSS-Consumer_B2C')
ORDER BY cq.SUBMIT_DATE DESC, cq.SEVERITY, cq.PRIORITY;
quit
;
