SELECT
 cq.CBS_MODULE, cq.SEVERITY, cq.PRIORITY, cq.ID, cq.TITLE, cq.SERVICE_NAME, s.NAME, cq.STATE, cq.SUBMIT_DATE,cq.CUSTOMER_NAME,cq.ASSIGN_TO_FULLNAME, cq.DBID, cq.DEFECT_TYPE
FROM CQ_RO.CBS_DEFECT cq, CQ_RO.STATEDEF s
WHERE
 (cq.PRODUCT_NAME='Legacy-Self-Care') AND (s.ID=cq.state) AND (DEFECT_TYPE<>'PR') AND (s.NAME <> 'Done')
ORDER BY cq.SUBMIT_DATE DESC, cq.SEVERITY, cq.PRIORITY;
quit
;
