SELECT
 cq.CBS_MODULE, cq.SEVERITY, cq.PRIORITY, cq.ID, cq.TITLE, cq.SERVICE_NAME, cq.STATE, cq.SUBMIT_DATE,cq.CUSTOMER_NAME,cq.ASSIGN_TO_FULLNAME, cq.DBID
FROM CQ_RO.CBS_DEFECT cq
WHERE
 (cq.PRODUCT_NAME='Legacy-Self-Care')
AND (cq.STATE <> 16778599) -- Done
ORDER BY cq.SUBMIT_DATE DESC, cq.SEVERITY, cq.PRIORITY;
quit
;
