CREATE TABLESPACE "NMY_CBU_REF_DATA" DATAFILE '&1/NMY_CBU_REF_DATA.dbf'
  SIZE 5M AUTOEXTEND ON NEXT 1M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 64K
/

CREATE TABLESPACE "NMY_CBU_REF_INDX" DATAFILE '&1/NMY_CBU_REF_INDX.dbf'
  SIZE 5M AUTOEXTEND ON NEXT 1M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 64K
/

CREATE TABLESPACE "NMY_CBU_LOAD" DATAFILE '&1/NMY_CBU_LOAD.dbf'
  SIZE 5M AUTOEXTEND ON NEXT 1M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 64K
/

CREATE TABLESPACE "NMY_CBU_USER_DATA" DATAFILE '&1/NMY_CBU_USER_DATA.dbf'
  SIZE 10M AUTOEXTEND ON NEXT 5M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K
/

CREATE TABLESPACE "NMY_CBU_USER_INDX" DATAFILE '&1/NMY_CBU_USER_INDX.dbf'
  SIZE 10M AUTOEXTEND ON NEXT 5M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
/

CREATE TABLESPACE "NMY_CBU_INVC_DATA" DATAFILE '&1/NMY_CBU_INVC_DATA.dbf'
  SIZE 10M AUTOEXTEND ON NEXT 5M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K
/

CREATE TABLESPACE "NMY_CBU_INVC_INDX" DATAFILE '&1/NMY_CBU_INVC_INDX.dbf'
  SIZE 10M AUTOEXTEND ON NEXT 5M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
/

CREATE TABLESPACE "NMY_CBU_SPLIT_DATA" DATAFILE '&1/NMY_CBU_SPLIT_DATA.dbf'
  SIZE 10M AUTOEXTEND ON NEXT 5M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K
/

CREATE TABLESPACE "NMY_CBU_SPLIT_INDX" DATAFILE '&1/NMY_CBU_SPLIT_INDX.dbf'
  SIZE 10M AUTOEXTEND ON NEXT 5M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
/

CREATE TABLESPACE "NMY_CBU_USAGE_DATA" DATAFILE '&1/NMY_CBU_USAGE_DATA.dbf'
  SIZE 20M AUTOEXTEND ON NEXT 10M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1024K
/

CREATE TABLESPACE "NMY_CBU_USAGE_INDX" DATAFILE '&1/NMY_CBU_USAGE_INDX.dbf'
  SIZE 20M AUTOEXTEND ON NEXT 10M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K
/

CREATE TEMPORARY TABLESPACE NMY_CBU_TEMP TEMPFILE '&1/NMY_CBU_TEMP.dbf'
  SIZE 20M AUTOEXTEND ON NEXT 10M EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
/

quit;
