drop tablespace NMY_CBU_REF_DATA INCLUDING CONTENTS AND DATAFILES
/

drop tablespace NMY_CBU_REF_INDX INCLUDING CONTENTS AND DATAFILES
/

drop tablespace NMY_CBU_LOAD INCLUDING CONTENTS AND DATAFILES
/

drop tablespace NMY_CBU_USER_DATA INCLUDING CONTENTS AND DATAFILES
/

drop tablespace NMY_CBU_USER_INDX INCLUDING CONTENTS AND DATAFILES
/

drop tablespace NMY_CBU_INVC_DATA INCLUDING CONTENTS AND DATAFILES
/

drop tablespace NMY_CBU_INVC_INDX INCLUDING CONTENTS AND DATAFILES
/

drop tablespace NMY_CBU_SPLIT_DATA INCLUDING CONTENTS AND DATAFILES
/

drop tablespace NMY_CBU_SPLIT_INDX INCLUDING CONTENTS AND DATAFILES
/

drop tablespace NMY_CBU_USAGE_DATA INCLUDING CONTENTS AND DATAFILES
/

drop tablespace NMY_CBU_USAGE_INDX INCLUDING CONTENTS AND DATAFILES
/

drop temporary tablespace NMY_CBU_TEMP INCLUDING CONTENTS AND DATAFILES
/

quit;
