DROP TABLESPACE INVOICE_DATA INCLUDING CONTENTS AND DATAFILES
/

DROP TABLESPACE INVOICE_INDEX INCLUDING CONTENTS AND DATAFILES
/

DROP TABLESPACE REQUEST_DATA INCLUDING CONTENTS AND DATAFILES
/

DROP TABLESPACE REQUEST_INDEX INCLUDING CONTENTS AND DATAFILES
/

DROP TABLESPACE USER_DATA INCLUDING CONTENTS AND DATAFILES
/

DROP TABLESPACE USER_INDEX INCLUDING CONTENTS AND DATAFILES
/

quit;
